holidays = [{'date': '01/01/2024', 'label': 'A�o Nuevo', 'type': 'inamovible'}, {'date': '12/02/2024', 'label': 'Carnaval', 'type': 'inamovible'}, {'date': '13/02/2024', 'label': 'Carnaval', 'type': 'inamovible'}, {'date': '24/03/2024', 'label': 'D�a Nacional de la Memoria por la Verdad y la Justicia', 'type': 'inamovible'}, {'date': '28/03/2024', 'label': 'Jueves Santo Festividad Cristiana', 'type': 'no_laborable'}, {'date': '29/03/2024', 'label': 'Viernes Santo Festividad Cristiana', 'type': 'inamovible'}, {'date': '01/04/2024', 'label': 'Feriado con fines tur�sticos', 'type': 'turistico'}, {'date': '02/04/2024', 'label': 'D�a del Veterano y de los Ca�dos en la Guerra de Malvinas', 'type': 'inamovible'}, {'date': '10/04/2024', 'label': 'Fiesta de la Ruptura del Ayuno del Sagrado Mes de Ramad�n (Id al-Fitr) (c)', 'type': 'no_laborable'}, {'date': '23/04/2024', 'label': 'Primeros dos d�as de la Pascua Jud�a (b)', 'type': 'no_laborable'}, {'date': '24/04/2024', 'label': 'Primeros dos d�as de la Pascua Jud�a (b)', 'type': 'no_laborable'}, {'date': '29/04/2024', 'label': '�ltimos dos d�as de la Pascua Jud�a (b)', 'type': 'no_laborable'}, {'date': '30/04/2024', 'label': '�ltimos dos d�as de la Pascua Jud�a (b)', 'type': 'no_laborable'}, {'date': '24/04/2024', 'label': 'D�a de acci�n por la tolerancia y el respeto entre los pueblos (a)', 'type': 'no_laborable'}, {'date': '01/05/2024', 'label': 'D�a del Trabajador', 'type': 'inamovible'}, {'date': '25/05/2024', 'label': 'D�a de la Revoluci�n de Mayo', 'type': 'inamovible'}, {
    'date': '16/06/2024', 'label': 'Fiesta del Sacrificio (c)', 'type': 'no_laborable'}, {'date': '17/06/2024', 'label': 'Paso a la Inmortalidad del Gral. Don Mart�n Miguel de G�emes', 'type': 'trasladable'}, {'date': '20/06/2024', 'label': 'Paso a la Inmortalidad del Gral. Manuel Belgrano', 'type': 'inamovible'}, {'date': '21/06/2024', 'label': 'Feriado con fines tur�sticos', 'type': 'turistico'}, {'date': '07/07/2024', 'label': 'A�o Nuevo Isl�mico (c)', 'type': 'no_laborable'}, {'date': '09/07/2024', 'label': 'D�a de la Independencia ', 'type': 'inamovible'}, {'date': '17/08/2024', 'label': 'Paso a la Inmortalidad del Gral. Jos� de San Mart�n', 'type': 'trasladable'}, {'date': '03/10/2024', 'label': 'A�o Nuevo Jud�o (b)', 'type': 'no_laborable'}, {'date': '04/10/2024', 'label': 'A�o Nuevo Jud�o (b)', 'type': 'no_laborable'}, {'date': '11/10/2024', 'label': 'Feriado con fines tur�sticos', 'type': 'turistico'}, {'date': '12/10/2024', 'label': 'D�a del Perd�n (b)', 'type': 'no_laborable'}, {'date': '12/10/2024', 'label': 'D�a del Respeto a la Diversidad Cultural', 'type': 'trasladable'}, {'date': '18/11/2024', 'label': 'D�a de la Soberan�a Nacional (20/11)', 'type': 'trasladable'}, {'date': '08/12/2024', 'label': 'Inmaculada Concepci�n de Mar�a', 'type': 'inamovible'}, {'date': '25/12/2024', 'label': 'Navidad', 'type': 'inamovible'}, {'date': '01/01/2025', 'label': 'A�o nuevo', 'type': 'inamovible'}]


def format_to_json(holidaysDict):
    jsonDictionary = {}

    for holiday in holidaysDict:
        print(holiday)
        jsonDictionary[holiday["date"]] = holiday

    return jsonDictionary


print(format_to_json(holidays))
